export const mockStatements = [
  {
    id: 'stmt-001',
    fileName: 'chase-march-2026.pdf',
    acquirer: 'Chase Merchant Services',
    period: 'Mar 2026',
    uploadDate: '12 Apr 2026',
    status: 'Parsed',
    parsingConfidence: 'high',
    rateConfidence: 'medium',
    dataAsOf: '12 Apr 2026',
    source: 'demo',
    parsedData: {
      billing_period: { from: '2026-03-01', to: '2026-03-31' },
      acquirer_name: 'Chase Merchant Services',
      merchant_id: 'MID-8842-HRTZ',
      total_transaction_volume: 355000,
      total_fees_charged: 6530,
      effective_rate: 1.84,
      interchange_fees: 3725,
      scheme_fees: 1302,
      service_fees: 1015,
      other_fees: 490,
      currency: 'USD',
      channel_split: {
        pos: { volume: 230250, fees: 3840, txn_count: 4120, avg_txn: 55.88 },
        cnp: { volume: 124750, fees: 2690, txn_count: 1840, avg_txn: 67.80 },
      },
      card_mix: { visa_debit: 42, visa_credit: 28, mc_debit: 15, mc_credit: 10, amex: 5 },
      fee_lines: [
        { type: 'Interchange — Visa Debit', rate: '0.05% + 22¢', amount: 710.15, card_type: 'Visa Debit', channel: 'POS', confidence: 'high', flagged: false },
        { type: 'Interchange — Visa Credit', rate: '0.10% + 22¢', amount: 515.50, card_type: 'Visa Credit', channel: 'POS', confidence: 'high', flagged: true },
        { type: 'Interchange — Mastercard Debit', rate: '0.05% + 22¢', amount: 427.35, card_type: 'MC Debit', channel: 'POS', confidence: 'high', flagged: false },
        { type: 'Interchange — Visa Debit (CNP)', rate: '0.05% + 22¢', amount: 312.40, card_type: 'Visa Debit', channel: 'Online', confidence: 'high', flagged: false },
        { type: 'Interchange — Visa Credit (CNP)', rate: '0.10% + 22¢', amount: 298.60, card_type: 'Visa Credit', channel: 'Online', confidence: 'medium', flagged: false },
        { type: 'Scheme fee — Visa', rate: '0.03%', amount: 67.78, card_type: 'Visa', channel: 'All', confidence: 'high', flagged: false },
        { type: 'Scheme fee — Mastercard', rate: '0.035%', amount: 52.30, card_type: 'Mastercard', channel: 'All', confidence: 'medium', flagged: false },
        { type: 'Scheme fee — Amex', rate: '0.15%', amount: 29.10, card_type: 'Amex', channel: 'All', confidence: 'high', flagged: false },
        { type: 'Service fee — POS (IC++)', rate: '0.42%', amount: 1490.50, card_type: 'All', channel: 'POS', confidence: 'high', flagged: true },
        { type: 'Service fee — Online', rate: '0.68%', amount: 848.30, card_type: 'All', channel: 'Online', confidence: 'high', flagged: true },
        { type: 'Amex direct (mark-up)', rate: '1.65%', amount: 647.65, card_type: 'Amex', channel: 'All', confidence: 'medium', flagged: false },
        { type: 'Auth fee', rate: '5¢ per txn', amount: 142.55, card_type: 'All', channel: 'All', confidence: 'high', flagged: false },
        { type: 'Refund fee', rate: '8¢ per txn', amount: 28.00, card_type: 'All', channel: 'All', confidence: 'medium', flagged: false },
        { type: 'PCI compliance monthly', rate: '—', amount: 37.49, card_type: '—', channel: '—', confidence: 'high', flagged: false },
        { type: 'Chargeback processing fee', rate: '$15 per chargeback', amount: 45.00, card_type: '—', channel: '—', confidence: 'high', flagged: false },
        { type: 'Minimum monthly service charge', rate: '—', amount: 0.00, card_type: '—', channel: '—', confidence: 'low', flagged: false },
      ],
    },
    discrepancies: [
      { line: 'Interchange pass-through', scheme: 'Visa Credit', agreed: '0.10% + 22¢', charged: '0.12% + 22¢', delta: '+0.02pp', impact: 160.25, flag: 'overcharge' },
      { line: 'Service fee — POS', scheme: 'All', agreed: '0.38%', charged: '0.42%', delta: '+0.04pp', impact: 92.10, flag: 'overcharge' },
      { line: 'Service fee — Online', scheme: 'All', agreed: '0.60%', charged: '0.68%', delta: '+0.08pp', impact: 99.80, flag: 'overcharge' },
      { line: 'Volume rebate (≥$250k)', scheme: 'All', agreed: '−0.05% of gross', charged: 'Not applied', delta: '−0.05pp', impact: 177.50, flag: 'rebate' },
      { line: 'Amex direct mark-up', scheme: 'Amex', agreed: '1.50%', charged: '1.65%', delta: '+0.15pp', impact: 58.90, flag: 'overcharge' },
      { line: 'Scheme fee — Mastercard', scheme: 'Mastercard', agreed: '0.035%', charged: '0.035%', delta: '0', impact: 0.00, flag: 'ok' },
    ],
    benchmarks: [
      { rank: 1, name: 'Stripe', save: 23000, rate: 1.42, conf: 'medium', dataAsOf: '12 Apr 2026', dataSourceTier: 'T2', blurb: 'Interchange++ with tiered volume discount; strong online performance. Ideal for CNP-heavy merchants.', referralApplicable: true, referralDisclosed: true },
      { rank: 2, name: 'Adyen', save: 17750, rate: 1.48, conf: 'high', dataAsOf: '12 Apr 2026', dataSourceTier: 'T1', blurb: 'Blended pricing; excellent scheme-fee optimisation for omnichannel. PSR-verified rate card.', referralApplicable: true, referralDisclosed: true },
      { rank: 3, name: 'Square', save: 9800, rate: 1.56, conf: 'low', dataAsOf: '28 Jan 2026', dataSourceTier: 'T3', blurb: 'Flat-rate pricing; limited benchmark data at your AOV band. Suitable for lower-volume POS.', referralApplicable: false, referralDisclosed: false },
    ],
    rateTrend: {
      labels: ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'],
      yours: [1.76, 1.79, 1.81, 1.79, 1.82, 1.84],
      panel: [1.44, 1.43, 1.42, 1.42, 1.42, 1.42],
      best: [1.30, 1.31, 1.30, 1.30, 1.31, 1.32],
    },
  },
  {
    id: 'stmt-002',
    fileName: 'chase-feb-2026.pdf',
    acquirer: 'Chase Merchant Services',
    period: 'Feb 2026',
    uploadDate: '14 Mar 2026',
    status: 'Parsed',
    parsingConfidence: 'high',
    rateConfidence: 'high',
    dataAsOf: '12 Apr 2026',
    source: 'demo',
    parsedData: {
      billing_period: { from: '2026-02-01', to: '2026-02-29' },
      acquirer_name: 'Chase Merchant Services',
      merchant_id: 'MID-8842-HRTZ',
      total_transaction_volume: 337000,
      total_fees_charged: 6148,
      effective_rate: 1.82,
      interchange_fees: 3520,
      scheme_fees: 1230,
      service_fees: 970,
      other_fees: 428,
      currency: 'USD',
      channel_split: {
        pos: { volume: 218050, fees: 3612, txn_count: 3901, avg_txn: 55.90 },
        cnp: { volume: 118950, fees: 2536, txn_count: 1752, avg_txn: 67.89 },
      },
      card_mix: { visa_debit: 41, visa_credit: 29, mc_debit: 15, mc_credit: 10, amex: 5 },
      fee_lines: [],
    },
    discrepancies: [],
    benchmarks: [],
    rateTrend: null,
  },
  {
    id: 'stmt-003',
    fileName: 'chase-jan-2026.pdf',
    acquirer: 'Chase Merchant Services',
    period: 'Jan 2026',
    uploadDate: '12 Feb 2026',
    status: 'Reviewing',
    parsingConfidence: 'medium',
    rateConfidence: 'medium',
    dataAsOf: '12 Apr 2026',
    source: 'demo',
    parsedData: {
      billing_period: { from: '2026-01-01', to: '2026-01-31' },
      acquirer_name: 'Chase Merchant Services',
      merchant_id: 'MID-8842-HRTZ',
      total_transaction_volume: 324000,
      total_fees_charged: 5801,
      effective_rate: 1.79,
      interchange_fees: 3320,
      scheme_fees: 1160,
      service_fees: 920,
      other_fees: 401,
      currency: 'USD',
      channel_split: {
        pos: { volume: 210600, fees: 3410, txn_count: 3762, avg_txn: 55.98 },
        cnp: { volume: 113400, fees: 2391, txn_count: 1686, avg_txn: 67.26 },
      },
      card_mix: { visa_debit: 43, visa_credit: 27, mc_debit: 16, mc_credit: 9, amex: 5 },
      fee_lines: [],
    },
    discrepancies: [],
    benchmarks: [],
    rateTrend: null,
  },
];

export const mockMerchantAgreements = [
  {
    id: 'agr-001',
    fileName: 'chase-merchant-agreement-2024.pdf',
    uploadDate: '15 Jan 2026',
    effectiveDate: '01 Feb 2024',
    version: 'v2.1',
    acquirer: 'Chase Merchant Services',
    status: 'Active',
    terms: {
      pos_service_rate: '0.38%',
      cnp_service_rate: '0.60%',
      interchange_passthrough: true,
      volume_rebate_threshold: 250000,
      volume_rebate_rate: '0.05%',
      monthly_min: 25.00,
      pci_fee: 37.49,
      amex_markup: '1.50%',
    },
  },
];

export const mockNotifications = [
  {
    id: 1,
    type: 'report_ready',
    title: 'Report ready — Chase Merchant Services Mar 2026',
    message: 'Your statement has been parsed. Effective rate 1.84% — 3 discrepancies found totalling $415.',
    date: '12 Apr 2026',
    read: false,
    emailSent: true,
  },
  {
    id: 2,
    type: 'stale_data',
    title: 'Benchmark data update — Square',
    message: 'Rate data for Square (T3 source) is now 94 days old. Marked amber — recommendations may be less accurate.',
    date: '10 Apr 2026',
    read: false,
    emailSent: false,
  },
  {
    id: 3,
    type: 'parse_complete',
    title: 'Parsing complete — Chase Merchant Services Feb 2026',
    message: 'Statement parsed successfully. 44 fee lines, overall confidence: High.',
    date: '14 Mar 2026',
    read: true,
    emailSent: true,
  },
  {
    id: 4,
    type: 'staleness_warn',
    title: 'Staleness alert — Clover rate data',
    message: 'Clover benchmark data is now 87 days old (amber threshold). Re-run your analysis to check for updated savings.',
    date: '10 Mar 2026',
    read: true,
    emailSent: false,
  },
  {
    id: 5,
    type: 'discrepancy',
    title: 'Discrepancy detected — $415 potential overcharge',
    message: 'Our analysis found 3 fee lines charged above your contracted rate. Review the discrepancy report to see details.',
    date: '12 Apr 2026',
    read: false,
    emailSent: true,
  },
];

export const mockSavedScenarios = [
  { id: 1, name: 'Steady Q2', vol: 120, aov: 48, debit: 58, credit: 32, growth: 8, effectiveRate: '1.84', date: 'Mar 28' },
  { id: 2, name: 'Summer bump', vol: 175, aov: 55, debit: 55, credit: 35, growth: 12, effectiveRate: '1.72', date: 'Apr 02' },
  { id: 3, name: 'New online SKU', vol: 225, aov: 62, debit: 50, credit: 40, growth: 18, effectiveRate: '1.68', date: 'Apr 11' },
];

export const acquirerDatabase = [
  { name: 'Stripe', tier: 'T2', region: 'US', lastUpdated: '12 Apr 2026', status: 'active', daysOld: 6, mccCoverage: 'Full', notes: 'SMB-reported data corroborated across 1,200+ submissions' },
  { name: 'Adyen', tier: 'T1', region: 'US', lastUpdated: '01 Apr 2026', status: 'active', daysOld: 17, mccCoverage: 'Full', notes: 'Interchange schedule + published rate card' },
  { name: 'Square', tier: 'T3', region: 'US', lastUpdated: '28 Jan 2026', status: 'stale', daysOld: 94, mccCoverage: 'Partial', notes: 'Floor rate from interchange schedules only — contact acquirer for current pricing' },
  { name: 'Chase Merchant Services', tier: 'T1', region: 'US', lastUpdated: '01 Apr 2026', status: 'active', daysOld: 17, mccCoverage: 'Full', notes: 'Interchange schedule + Visa/MC scheme data' },
  { name: 'PayPal / Braintree', tier: 'T2', region: 'US', lastUpdated: '05 Apr 2026', status: 'active', daysOld: 13, mccCoverage: 'Full', notes: 'SMB-reported, cross-validated with published rate pages' },
  { name: 'Worldpay (FIS)', tier: 'T1', region: 'US', lastUpdated: '08 Apr 2026', status: 'active', daysOld: 10, mccCoverage: 'Full', notes: 'Regulatory disclosure data + published interchange schedule' },
  { name: 'Heartland', tier: 'T2', region: 'US', lastUpdated: '15 Mar 2026', status: 'active', daysOld: 34, mccCoverage: 'Partial', notes: 'SMB-submitted data — 340 validated submissions' },
  { name: 'First Data (Fiserv)', tier: 'T1', region: 'US', lastUpdated: '01 Apr 2026', status: 'active', daysOld: 17, mccCoverage: 'Full', notes: 'Interchange schedule + regulatory disclosure' },
  { name: 'Elavon', tier: 'T2', region: 'US', lastUpdated: '20 Mar 2026', status: 'active', daysOld: 29, mccCoverage: 'Full', notes: 'SMB-reported, corroborated with scheme data' },
  { name: 'Clover', tier: 'T3', region: 'US', lastUpdated: '15 Feb 2026', status: 'stale', daysOld: 87, mccCoverage: 'Partial', notes: 'Estimated floor rate only — amber staleness threshold exceeded' },
];

export const DATA_TIER_LABELS = {
  T1: { label: 'T1 — Regulatory / Interchange', color: 'leaf', description: 'Published interchange schedules or regulatory disclosure. Highest confidence.' },
  T2: { label: 'T2 — SMB-Reported (corroborated)', color: 'teal', description: 'Anonymised SMB submissions, cross-validated with published data. Medium-high confidence.' },
  T3: { label: 'T3 — Floor rate estimate', color: 'amber', description: 'Interchange floor only — actual acquirer margin unknown. Contact acquirer for current pricing.' },
  T4: { label: 'T4 — Open Banking feed', color: 'teal', description: 'Real-time account data feed (where available). High confidence, continuous.' },
  T5: { label: 'T5 — Acquirer partnership', color: 'leaf', description: 'Acquirer-provided rate card. Voluntary participation; does not influence recommendation ranking.' },
};
