/** Rich demo statements: `demoParsedFallback` uses the first row when live parse fails; `mockStatements` is empty by default. */
export const statementFormulaFixtures = [
  {
    id: 'stmt-001',
    fileName: 'statement-march-2026.pdf',
    acquirer: 'Sample Processor LLC',
    period: 'Mar 2026',
    uploadDate: '12 Apr 2026',
    status: 'Parsed',
    parsingConfidence: 'high',
    rateConfidence: 'medium',
    dataAsOf: '12 Apr 2026',
    source: 'demo',
    fileType: 'pdf',
    parsedData: {
      file_type: 'pdf',
      billing_period: { from: '2026-03-01', to: '2026-03-31' },
      acquirer_name: 'Sample Processor LLC',
      merchant_id: 'MID-8842-HRTZ',
      total_transaction_volume: 355000,
      total_fees_charged: 6530,
      effective_rate: 1.84,
      interchange_fees: 3725,
      scheme_fees: 1302,
      service_fees: 1015,
      other_fees: 490,
      currency: 'USD',
      channel_split: {
        pos: {
          channel_label: 'POS (in-store)',
          volume: 230250,
          refund_volume: 920,
          fees: 3840,
          txn_count: 4120,
          avg_txn: 55.88,
          net_settled_volume: 225490,
        },
        cnp: {
          channel_label: 'E-commerce (online)',
          volume: 124750,
          refund_volume: 410,
          fees: 2690,
          txn_count: 1840,
          avg_txn: 67.8,
          net_settled_volume: 121650,
        },
      },
      refund_volume: 1330,
      pos_net_deposit_volume: 225490,
      ecomm_net_deposit_volume: 121650,
      reconciliation_total_deposits: 347140,
      bank_credits_total_verified: 345800,
      reconciliation_variance: 1340,
      card_mix: { mix_key_1: 42, mix_key_2: 28, mix_key_3: 15, mix_key_4: 10, mix_key_5: 5 },
      fee_lines: [
        { type: 'Interchange — mix_key_1', rate: '0.05% + 22¢', amount: 710.15, card_type: 'mix_key_1', channel: 'POS', confidence: 'high', flagged: false },
        { type: 'Interchange — mix_key_2', rate: '0.10% + 22¢', amount: 515.50, card_type: 'mix_key_2', channel: 'POS', confidence: 'high', flagged: true },
        { type: 'Interchange — mix_key_3', rate: '0.05% + 22¢', amount: 427.35, card_type: 'mix_key_3', channel: 'POS', confidence: 'high', flagged: false },
        { type: 'Interchange — mix_key_1 (CNP)', rate: '0.05% + 22¢', amount: 312.40, card_type: 'mix_key_1', channel: 'Online', confidence: 'high', flagged: false },
        { type: 'Interchange — mix_key_2 (CNP)', rate: '0.10% + 22¢', amount: 298.60, card_type: 'mix_key_2', channel: 'Online', confidence: 'medium', flagged: false },
        { type: 'Scheme fee — mix_key_1', rate: '0.03%', amount: 67.78, card_type: 'mix_key_1', channel: 'All', confidence: 'high', flagged: false },
        { type: 'Scheme fee — mix_key_3', rate: '0.035%', amount: 52.30, card_type: 'mix_key_3', channel: 'All', confidence: 'medium', flagged: false },
        { type: 'Scheme fee — mix_key_5', rate: '0.15%', amount: 29.10, card_type: 'mix_key_5', channel: 'All', confidence: 'high', flagged: false },
        { type: 'Service fee — POS (IC++)', rate: '0.42%', amount: 1490.50, card_type: 'all', channel: 'POS', confidence: 'high', flagged: true },
        { type: 'Service fee — Online', rate: '0.68%', amount: 848.30, card_type: 'all', channel: 'Online', confidence: 'high', flagged: true },
        { type: 'mix_key_5 direct (mark-up)', rate: '1.65%', amount: 647.65, card_type: 'mix_key_5', channel: 'All', confidence: 'medium', flagged: false },
        { type: 'Auth fee', rate: '5¢ per txn', amount: 142.55, card_type: 'all', channel: 'All', confidence: 'high', flagged: false },
        { type: 'Refund fee', rate: '8¢ per txn', amount: 28.00, card_type: 'all', channel: 'All', confidence: 'medium', flagged: false },
        { type: 'PCI compliance monthly', rate: '—', amount: 37.49, card_type: '—', channel: '—', confidence: 'high', flagged: false },
        { type: 'Chargeback processing fee', rate: '$15 per chargeback', amount: 45.00, card_type: '—', channel: '—', confidence: 'high', flagged: false },
        { type: 'Minimum monthly service charge', rate: '—', amount: 0.00, card_type: '—', channel: '—', confidence: 'low', flagged: false },
      ],
    },
    discrepancies: [
      {
        label: 'Settlement lag — last batch of month',
        amount: -820,
        explanation:
          'Processor payouts dated on the period end often post T+1 or T+2; they may appear on the next bank statement.',
      },
      {
        label: 'Cash sales not in card settlement totals',
        amount: -520,
        explanation:
          'Cash drawer activity is not included in card-net payout lines until deposited separately to the bank.',
      },
    ],
    benchmarks: [],
    rateTrend: null,
  },
  {
    id: 'stmt-002',
    fileName: 'statement-feb-2026.pdf',
    acquirer: 'Sample Processor LLC',
    period: 'Feb 2026',
    uploadDate: '14 Mar 2026',
    status: 'Parsed',
    parsingConfidence: 'high',
    rateConfidence: 'high',
    dataAsOf: '12 Apr 2026',
    source: 'demo',
    fileType: 'pdf',
    parsedData: {
      file_type: 'pdf',
      billing_period: { from: '2026-02-01', to: '2026-02-29' },
      acquirer_name: 'Sample Processor LLC',
      merchant_id: 'MID-8842-HRTZ',
      total_transaction_volume: 337000,
      total_fees_charged: 6148,
      effective_rate: 1.82,
      interchange_fees: 3520,
      scheme_fees: 1230,
      service_fees: 970,
      other_fees: 428,
      currency: 'USD',
      channel_split: {
        pos: { volume: 218050, fees: 3612, txn_count: 3901, avg_txn: 55.90 },
        cnp: { volume: 118950, fees: 2536, txn_count: 1752, avg_txn: 67.89 },
      },
      card_mix: { mix_key_1: 41, mix_key_2: 29, mix_key_3: 15, mix_key_4: 10, mix_key_5: 5 },
      fee_lines: [],
    },
    discrepancies: [],
    benchmarks: [],
    rateTrend: null,
  },
  {
    id: 'stmt-003',
    fileName: 'statement-jan-2026.pdf',
    acquirer: 'Sample Processor LLC',
    period: 'Jan 2026',
    uploadDate: '12 Feb 2026',
    status: 'Reviewing',
    parsingConfidence: 'medium',
    rateConfidence: 'medium',
    dataAsOf: '12 Apr 2026',
    source: 'demo',
    fileType: 'pdf',
    parsedData: {
      file_type: 'pdf',
      billing_period: { from: '2026-01-01', to: '2026-01-31' },
      acquirer_name: 'Sample Processor LLC',
      merchant_id: 'MID-8842-HRTZ',
      total_transaction_volume: 324000,
      total_fees_charged: 5801,
      effective_rate: 1.79,
      interchange_fees: 3320,
      scheme_fees: 1160,
      service_fees: 920,
      other_fees: 401,
      currency: 'USD',
      channel_split: {
        pos: { volume: 210600, fees: 3410, txn_count: 3762, avg_txn: 55.98 },
        cnp: { volume: 113400, fees: 2391, txn_count: 1686, avg_txn: 67.26 },
      },
      card_mix: { mix_key_1: 43, mix_key_2: 27, mix_key_3: 16, mix_key_4: 9, mix_key_5: 5 },
      fee_lines: [],
    },
    discrepancies: [],
    benchmarks: [],
    rateTrend: null,
  },
];

export const mockStatements = [];

/** When live parse fails, `parseStatementUploadFile` finalizes this shape as demo preview data. */
export const demoParsedFallback = JSON.parse(JSON.stringify(statementFormulaFixtures[0].parsedData));

export const mockSavedScenarios = [
  { id: 1, name: 'Steady Q2', vol: 120, aov: 48, debit: 58, credit: 32, growth: 8, effectiveRate: '1.84', date: 'Mar 28' },
  { id: 2, name: 'Summer bump', vol: 175, aov: 55, debit: 55, credit: 35, growth: 12, effectiveRate: '1.72', date: 'Apr 02' },
  { id: 3, name: 'New online SKU', vol: 225, aov: 62, debit: 50, credit: 40, growth: 18, effectiveRate: '1.68', date: 'Apr 11' },
];

export const acquirerDatabase = [
  { name: 'Acquirer Alpha', tier: 'T2', region: 'US', lastUpdated: '12 Apr 2026', status: 'active', daysOld: 6, mccCoverage: 'Full', notes: 'Illustrative tier — replace with your processor data.' },
  { name: 'Acquirer Beta', tier: 'T1', region: 'US', lastUpdated: '01 Apr 2026', status: 'active', daysOld: 17, mccCoverage: 'Full', notes: 'Illustrative tier — published schedule + disclosure.' },
  { name: 'Acquirer Gamma', tier: 'T3', region: 'US', lastUpdated: '28 Jan 2026', status: 'stale', daysOld: 94, mccCoverage: 'Partial', notes: 'Illustrative floor estimate — confirm pricing with your acquirer.' },
  { name: 'Acquirer Kappa', tier: 'T1', region: 'US', lastUpdated: '01 Apr 2026', status: 'active', daysOld: 17, mccCoverage: 'Full', notes: 'Illustrative published-schedule profile.' },
  { name: 'Acquirer Delta', tier: 'T2', region: 'US', lastUpdated: '05 Apr 2026', status: 'active', daysOld: 13, mccCoverage: 'Full', notes: 'Illustrative SMB-reported profile.' },
  { name: 'Acquirer Epsilon', tier: 'T1', region: 'US', lastUpdated: '08 Apr 2026', status: 'active', daysOld: 10, mccCoverage: 'Full', notes: 'Illustrative disclosure-based profile.' },
  { name: 'Acquirer Zeta', tier: 'T2', region: 'US', lastUpdated: '15 Mar 2026', status: 'active', daysOld: 34, mccCoverage: 'Partial', notes: 'Illustrative partial-coverage profile.' },
  { name: 'Acquirer Eta', tier: 'T1', region: 'US', lastUpdated: '01 Apr 2026', status: 'active', daysOld: 17, mccCoverage: 'Full', notes: 'Illustrative regulatory disclosure profile.' },
  { name: 'Acquirer Theta', tier: 'T2', region: 'US', lastUpdated: '20 Mar 2026', status: 'active', daysOld: 29, mccCoverage: 'Full', notes: 'Illustrative corroborated profile.' },
  { name: 'Acquirer Iota', tier: 'T3', region: 'US', lastUpdated: '15 Feb 2026', status: 'stale', daysOld: 87, mccCoverage: 'Partial', notes: 'Illustrative estimate — confirm with acquirer.' },
];

export const DATA_TIER_LABELS = {
  T1: { label: 'T1 — Regulatory / Interchange', color: 'leaf', description: 'Published interchange schedules or regulatory disclosure. Highest confidence.' },
  T2: { label: 'T2 — SMB-Reported (corroborated)', color: 'teal', description: 'Anonymised SMB submissions, cross-validated with published data. Medium-high confidence.' },
  T3: { label: 'T3 — Floor rate estimate', color: 'amber', description: 'Interchange floor only — actual acquirer margin unknown. Contact acquirer for current pricing.' },
  T4: { label: 'T4 — Open Banking feed', color: 'teal', description: 'Real-time account data feed (where available). High confidence, continuous.' },
  T5: { label: 'T5 — Acquirer partnership', color: 'leaf', description: 'Acquirer-provided rate card. Voluntary participation.' },
};
